/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const OrderItem = IDL.Record({
  'id' : IDL.Nat,
  'orderId' : IDL.Nat,
  'quantity' : IDL.Nat,
  'price' : IDL.Nat,
  'menuItemId' : IDL.Nat,
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });
export const OrderStatus = IDL.Variant({
  'preparing' : IDL.Null,
  'cancelled' : IDL.Null,
  'pending' : IDL.Null,
  'outForDelivery' : IDL.Null,
  'delivered' : IDL.Null,
  'confirmed' : IDL.Null,
});
export const Restaurant = IDL.Record({
  'id' : IDL.Nat,
  'name' : IDL.Text,
  'description' : IDL.Text,
});
export const MenuItem = IDL.Record({
  'id' : IDL.Nat,
  'name' : IDL.Text,
  'description' : IDL.Text,
  'restaurantId' : IDL.Nat,
  'price' : IDL.Nat,
});
export const CartItem = IDL.Record({
  'quantity' : IDL.Nat,
  'menuItemId' : IDL.Nat,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'getAllOrderItems' : IDL.Func([IDL.Nat], [IDL.Vec(OrderItem)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getOrderStatus' : IDL.Func([IDL.Nat], [IDL.Opt(OrderStatus)], ['query']),
  'getRestaurant' : IDL.Func([IDL.Nat], [IDL.Opt(Restaurant)], ['query']),
  'getRestaurantMenu' : IDL.Func([IDL.Nat], [IDL.Vec(MenuItem)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'listRestaurants' : IDL.Func([], [IDL.Vec(Restaurant)], ['query']),
  'placeOrder' : IDL.Func([IDL.Nat, IDL.Vec(CartItem)], [IDL.Nat], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'updateOrderStatus' : IDL.Func([IDL.Nat, OrderStatus], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const OrderItem = IDL.Record({
    'id' : IDL.Nat,
    'orderId' : IDL.Nat,
    'quantity' : IDL.Nat,
    'price' : IDL.Nat,
    'menuItemId' : IDL.Nat,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  const OrderStatus = IDL.Variant({
    'preparing' : IDL.Null,
    'cancelled' : IDL.Null,
    'pending' : IDL.Null,
    'outForDelivery' : IDL.Null,
    'delivered' : IDL.Null,
    'confirmed' : IDL.Null,
  });
  const Restaurant = IDL.Record({
    'id' : IDL.Nat,
    'name' : IDL.Text,
    'description' : IDL.Text,
  });
  const MenuItem = IDL.Record({
    'id' : IDL.Nat,
    'name' : IDL.Text,
    'description' : IDL.Text,
    'restaurantId' : IDL.Nat,
    'price' : IDL.Nat,
  });
  const CartItem = IDL.Record({ 'quantity' : IDL.Nat, 'menuItemId' : IDL.Nat });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'getAllOrderItems' : IDL.Func([IDL.Nat], [IDL.Vec(OrderItem)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getOrderStatus' : IDL.Func([IDL.Nat], [IDL.Opt(OrderStatus)], ['query']),
    'getRestaurant' : IDL.Func([IDL.Nat], [IDL.Opt(Restaurant)], ['query']),
    'getRestaurantMenu' : IDL.Func([IDL.Nat], [IDL.Vec(MenuItem)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'listRestaurants' : IDL.Func([], [IDL.Vec(Restaurant)], ['query']),
    'placeOrder' : IDL.Func([IDL.Nat, IDL.Vec(CartItem)], [IDL.Nat], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'updateOrderStatus' : IDL.Func([IDL.Nat, OrderStatus], [], []),
  });
};

export const init = ({ IDL }) => { return []; };